site_name: Elypso Docs

repo_url: "https://github.com/Lost-Empire-Entertainment/Engine-website"
remote_branch: indev

theme:
  name: material
  palette:
    primary: light blue
    accent: teal
  features:
    - content.code.copy  # ✅ Correctly indented under "theme"
  logo: 'assets/Logo.gif'  # Correct logo path

extra_css:
  - assets/custom.css  # Correct custom.css path

extra:
  font:
    text: Roboto
    code: Fira Code
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true  # Enables line numbers
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.superfences  # Enables advanced code blocks

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Docs:
      - Installation: installation.md
      - Quickstart: quickstart.md
      - API: api.md
      - FAQ: faq.md
